Repository caraml-dev/turing, pull requests merged in 2022-03, with the labels that each got.

#177 Standardize labels for kube objects
  api/turing/batch/ensembling/controller.go
  api/turing/cluster/controller.go
  api/turing/cluster/controller_test.go
  api/turing/cluster/mocks/controller.go
  api/turing/cluster/models.go
  api/turing/cluster/pvc.go
  api/turing/cluster/pvc_test.go
  api/turing/cluster/role.go
  api/turing/cluster/role_binding.go
  api/turing/cluster/role_binding_test.go
  api/turing/cluster/role_test.go
  api/turing/cluster/secret.go
  api/turing/cluster/secret_test.go
  api/turing/cluster/service_account.go
  api/turing/cluster/service_account_test.go
  api/turing/cluster/servicebuilder/fluentd.go
  api/turing/cluster/servicebuilder/fluentd_test.go
  api/turing/cluster/servicebuilder/plugins_server.go
  api/turing/cluster/servicebuilder/plugins_server_test.go
  api/turing/cluster/servicebuilder/router.go
  api/turing/cluster/servicebuilder/router_test.go
  api/turing/cluster/servicebuilder/service_builder.go
  api/turing/cluster/servicebuilder/service_builder_test.go
  api/turing/service/router_deployment_service.go
  api/turing/service/router_deployment_service_test.go
  infra/charts/turing/Chart.yaml
  infra/charts/turing/templates/_helpers.tpl
  infra/charts/turing/templates/cluster-role-binding.yaml
  infra/charts/turing/templates/cluster-role.yaml
  infra/charts/turing/templates/deployment.yaml
  infra/charts/turing/templates/ingress.yaml
  infra/charts/turing/templates/openapi-override-configmap.yaml
  infra/charts/turing/templates/secrets.yaml
  infra/charts/turing/templates/service-account.yaml
  infra/charts/turing/templates/virtualservice-mlp.yaml
Labels: enhancement

#185 [Chart] Turing chart version 0.2.7
  infra/charts/turing/Chart.yaml
  infra/charts/turing/README.md
  infra/charts/turing/values.yaml
Labels: enhancement

#184 [Documentation]: Experiment Engine plugins
  .github/workflows/turing.yaml
  api/e2e/test/00_all_e2e_test.go
  api/e2e/test/01_create_router_test.go
  api/e2e/test/02_update_router_invalid_test.go
  api/e2e/test/03_create_router_version_test.go
  api/e2e/test/08_deploy_router_with_traffic_rules_test.go
  api/e2e/test/helpers_api_test.go
  api/e2e/test/testdata/create_router_nop_logger_proprietary_exp.json.tmpl
  engines/experiment/docs/assets/exp_manager_plugin_diagram.png
  engines/experiment/docs/assets/exp_runner_plugin_diagram.png
  engines/experiment/docs/rpc_plugins.md
  engines/experiment/examples/plugins/hardcoded/Dockerfile
  engines/experiment/examples/plugins/hardcoded/Makefile
  engines/experiment/examples/plugins/hardcoded/cmd/main.go
  engines/experiment/examples/plugins/hardcoded/config.go
  engines/experiment/examples/plugins/hardcoded/configs/plugin_config_example.yaml
  engines/experiment/examples/plugins/hardcoded/configs/router_config_example.json
  engines/experiment/examples/plugins/hardcoded/go.mod
  engines/experiment/examples/plugins/hardcoded/go.sum
  engines/experiment/examples/plugins/hardcoded/manager.go
  engines/experiment/examples/plugins/hardcoded/runner.go
  engines/experiment/examples/plugins/hardcoded/utils/hash.go
  engines/experiment/log/hclog.go
  engines/experiment/log/hclog/hclog.go
  engines/experiment/log/log.go
  engines/experiment/log/zap.go
  infra/e2e/turing.values.yaml
Labels: documentation

#189 [BUG] Fix End-to-End test suite
  api/e2e/test/01_create_router_test.go
  engines/experiment/examples/plugins/hardcoded/go.mod
  engines/experiment/examples/plugins/hardcoded/runner_test.go
Labels: bug
