Repository caraml-dev/turing, pull requests merged in 2024-05, with the labels that each got.

#378 fix(turing): Add new autoscaling target processing for concurrency
  api/turing/cluster/knative_service.go
  api/turing/cluster/knative_service_test.go
Labels: type: bug

#377 fix(sdk): Remove exp engine passkey when retrieving routers from the API server
  engines/pyfunc-ensembler-service/requirements.dev.txt
  sdk/requirements.dev.txt
  sdk/tests/router/config/router_version_test.py
  sdk/turing/router/config/router_config.py
Labels: type: bug

#376 Ensembler Image Building API
  .github/workflows/sdk.yaml
  .github/workflows/turing.yaml
  api/api/openapi-sdk.yaml
  api/api/openapi.bundle.yaml
  api/api/openapi.yaml
  api/api/specs/ensembler-images.yaml
  api/go.mod
  api/go.sum
  api/turing/api/appcontext.go
  api/turing/api/appcontext_test.go
  api/turing/api/ensembler_images_api.go
  api/turing/api/ensembler_images_api_test.go
  api/turing/api/request/ensembler_images.go
  api/turing/batch/ensembling/runner.go
  api/turing/batch/ensembling/runner_test.go
  api/turing/imagebuilder/ensembler.go
  api/turing/imagebuilder/imagebuilder.go
  api/turing/imagebuilder/imagebuilder_test.go
  api/turing/imagebuilder/mocks/image_builder.go
  api/turing/models/ensembler.go
  api/turing/server/api.go
  api/turing/service/ensembler_image_service.go
  api/turing/service/ensembler_image_service_test.go
  api/turing/service/mocks/alert_service.go
  api/turing/service/mocks/crypto_service.go
  api/turing/service/mocks/ensembler_images_service.go
  api/turing/service/mocks/ensemblers_service.go
  api/turing/service/mocks/ensembling_job_service.go
  api/turing/service/mocks/event_service.go
  api/turing/service/mocks/experiments_service.go
  api/turing/service/mocks/mlp_service.go
  api/turing/service/mocks/pod_log_service.go
  api/turing/service/mocks/router_monitoring_service.go
  api/turing/service/mocks/router_versions_service.go
  api/turing/service/mocks/routers_service.go
  api/turing/service/mocks/u_func.go
  engines/pyfunc-ensembler-job/requirements.dev.txt
  engines/pyfunc-ensembler-service/requirements.dev.txt
  sdk/Makefile
  sdk/requirements.dev.txt
  sdk/requirements.txt
  sdk/tests/conftest.py
  sdk/tests/ensembler_image_test.py
  sdk/tests/ensembler_test.py
  sdk/turing/__init__.py
  sdk/turing/ensembler_image.py
  sdk/turing/generated/api/ensembler_images_api.py
  sdk/turing/generated/apis/__init__.py
  sdk/turing/generated/model/build_ensembler_image_request.py
  sdk/turing/generated/model/ensembler_image.py
  sdk/turing/generated/model/ensembler_image_runner_type.py
  sdk/turing/generated/model/ensembler_images.py
  sdk/turing/generated/model/image_building_job_state.py
  sdk/turing/generated/model/image_building_job_status.py
  sdk/turing/generated/models/__init__.py
  sdk/turing/session.py
Labels: enhancement, type: feature

#379 fix(api): Refactor JobState to string
  api/turing/api/ensembler_images_api.go
  api/turing/imagebuilder/imagebuilder.go
Labels: enhancement

#380 fix(api,ui): Fix autoscaling target parsing
  api/turing/cluster/knative_service.go
  api/turing/cluster/knative_service_test.go
  ui/src/router/components/form/components/autoscaling_policy/AutoscalingPolicyPanel.js
  ui/src/router/components/form/validation/schema.js
  ui/src/services/version/RouterVersion.js
Labels: type: bug
