Repository caraml-dev/turing, pull requests merged in 2024-07, with the labels that each got.

#383 feat(ui): Add stackdriver links to logs tab
  ui/src/components/pod_logs_viewer/PodLogsViewer.js
  ui/src/config.js
  ui/src/router/details/RouterDetailsView.js
  ui/src/router/details/logs/RouterLogsView.js
  ui/src/utils/createStackdriverUrl.js
Labels: enhancement

#385 fix(api): Remove regex check for autoscaling target in autogenerated files
  api/api/openapi.bundle.yaml
  api/api/specs/routers.yaml
  api/turing/generated/model_big_query_dataset.go
  api/turing/generated/model_big_query_dataset_config.go
  api/turing/generated/model_big_query_sink.go
  api/turing/generated/model_big_query_sink_config.go
  api/turing/generated/model_dataset.go
  api/turing/generated/model_ensembler_config.go
  api/turing/generated/model_ensembler_config_kind.go
  api/turing/generated/model_ensembler_infra_config.go
  api/turing/generated/model_ensembling_job_ensembler_spec.go
  api/turing/generated/model_ensembling_job_ensembler_spec_result.go
  api/turing/generated/model_ensembling_job_meta.go
  api/turing/generated/model_ensembling_job_prediction_source.go
  api/turing/generated/model_ensembling_job_result_type.go
  api/turing/generated/model_ensembling_job_sink.go
  api/turing/generated/model_ensembling_job_source.go
  api/turing/generated/model_ensembling_job_spec.go
  api/turing/generated/model_ensembling_resources.go
  api/turing/generated/model_env_var.go
  api/turing/generated/model_save_mode.go
  api/turing/models/autoscaling_policy.go
  api/turing/validation/validator_test.go
  sdk/turing/generated/model/autoscaling_policy.py
Labels: type: bug

#384 chore(ui): Upgrade UI dependencies
  .github/actions/build-cluster-init/action.yaml
  .github/actions/setup-test-cluster/action.yaml
  .github/workflows/cluster-init.yaml
  .github/workflows/fluentd-plugin.yaml
  .github/workflows/helm-chart.yaml
  .github/workflows/pyfunc-ensembler-job.yaml
  .github/workflows/pyfunc-ensembler-service.yaml
  .github/workflows/sdk.yaml
  .github/workflows/turing-publish.yaml
  .github/workflows/turing.yaml
  ui/craco.config.js
  ui/package.json
  ui/src/bootstrap.js
  ui/src/components/collapsible_badge_group/CollapsibleBadgeGroup.js
  ui/src/components/config_section/ConfigSectionTitle.js
  ui/src/components/config_section/index.scss
  ui/src/components/expandable_container/ExpandableContainer.js
  ui/src/ensembler/list/ListEnsemblersView.js
  ui/src/jobs/details/EnsemblingJobDetailsView.js
  ui/src/jobs/details/config/components/bq_options_table/BigQueryOptionsTable.js
  ui/src/jobs/details/config/configuration_section/misc_table/MiscConfigSection.js
  ui/src/jobs/details/config/configuration_section/resource_request_table/ResourceRequestConfigTable.js
  ui/src/jobs/details/config/sink_config_section/bq_config_section/BigQuerySinkConfigTable.js
  ui/src/jobs/details/config/sink_config_section/sink_config_table/SinkConfigTable.js
  ui/src/jobs/details/config/source_config_section/bq_config_section/BigQueryDatasetSection.js
  ui/src/jobs/details/config/source_config_section/bq_config_section/BigQueryDatasetSection.scss
  ui/src/jobs/list/ListEnsemblingJobsTable.js
  ui/src/jobs/list/ListEnsemblingJobsView.js
  ui/src/router/components/configuration/components/LoggingConfigSection.js
  ui/src/router/components/configuration/components/ResourcesConfigTable.js
  ui/src/router/components/configuration/components/docker_config_section/ContainerConfigTable.js
  ui/src/router/components/configuration/components/docker_config_section/EnvVariablesConfigTable.js
  ui/src/router/components/configuration/components/experiment_config_section/credentials/CredentialsConfigSection.js
  ui/src/router/components/configuration/components/experiment_config_section/credentials/CredentialsConfigSection.scss
  ui/src/router/components/configuration/components/experiment_config_section/variables/VariablesConfigTable.js
  ui/src/router/components/configuration/components/experiment_config_section/variables/VariablesConfigTable.scss
  ui/src/router/components/configuration/components/pyfunc_config_section/PyFuncConfigTable.js
  ui/src/router/components/configuration/components/route_config_section/RouteConfigSection.js
  ui/src/router/components/configuration/components/router_config_section/RoutesConfigTable.js
  ui/src/router/components/configuration/components/router_config_section/RulesConfigTable.js
  ui/src/router/components/configuration/components/standard_config_section/RoutingStrategyConfigSection.js
  ui/src/router/components/configuration/components/standard_config_section/TreatmentMappingConfigSection.js
  ui/src/router/components/form/components/docker_config/EnvVariablesPanel.js
  ui/src/router/details/RouterDetailsView.js
  ui/src/router/versions/details/RouterVersionDetailsView.js
  ui/src/router/versions/list/ListRouterVersionsTable.js
  ui/yarn.lock
Labels: type: maintenance

#386 fix(ui): Revert upgrade to react-lazylog
  .github/workflows/turing.yaml
  ui/package.json
  ui/src/components/pod_logs_viewer/PodLogsViewer.js
  ui/src/components/pod_logs_viewer/PodLogsViewer.scss
  ui/yarn.lock
Labels: type: bug

#387 fix(ui): Fix yup validation bugs
  .github/workflows/turing.yaml
  ui/package.json
  ui/src/components/validation.js
  ui/src/router/components/form/components/experiment_config/components/client_config/ClientConfigPanel.js
  ui/src/router/components/form/components/experiment_config/validation/schema.js
  ui/src/router/components/form/validation/schema.js
  ui/yarn.lock
Labels: type: bug

#388 fix(ui): Fix incorrect yup schema
  ui/src/router/components/form/validation/schema.js
Labels: type: bug
