Repository caraml-dev/turing, pull requests merged in 2025-07, with the labels that each got.

#407 chore: retrieve google sa in ensembling job only if it's specified
  api/turing/batch/ensembling/controller.go
Labels: type: maintenance

#411 fix(ensembler): Add pipenv installation
  engines/pyfunc-ensembler-job/Makefile
  engines/pyfunc-ensembler-service/Makefile
Labels: type: bug

#414 feat(ui): add mustache templating in pod log url
  ui/package.json
  ui/src/components/pod_logs_viewer/PodLogsViewer.js
  ui/src/config.js
  ui/src/router/details/logs/RouterLogsView.js
  ui/src/utils/createLogUrl.js
  ui/yarn.lock
Labels: enhancement
